version: "3"

services:
  postgres:
    container_name: "fu-bib-postgres"
    restart: unless-stopped
    image: "postgres:13"
    ports:
      - "15432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: postgres

  api:
    container_name: "fu-bib-backend"
    restart: unless-stopped
    image: node:16
    command: yarn run dev
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/:rw
    working_dir: /srv
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@fu-bib-postgres/postgres?connect_timeout=300

volumes:
  pgdata: {}
